/**
 * Created by Nir on 24/02/2017.
 */
var mongoose = require('mongoose');
var Schema = mongoose.Schema;



/*
 submission is the object which is generated by the student that submitted the assignment.
 it can also be generated by an higher priority user that is submitting the assignment on behalf
 of another person (e.g. on behalf of one of the students).
 this object will hold crucial data such as the parent assignment (submission is an assignment submission)
 it will hold a list of all the errors captured during the examination process.
 */

var SubmissionSchema = new Schema( {
    // parent_assignment: { type : Schema.ObjectId, ref: 'Assignment' },
    checked: {type: Boolean},
    submission_name : {type: String }, // the user will be asked to enter a title for his submission
    // standard_errors_instances: [{ type : Schema.ObjectId, ref: 'ErrorInstance' }], //list of all errors captured
    grade: {type: Number,  min: 0, max: 100 , default: 0},
    description: { type : String },
    submitted_by: { type : String },
    date_created: { type: Date, default: Date.now },
    path :{type: String}
});


//saving the submission in db
SubmissionSchema.pre('save' , function (next) {
    next();
});

SubmissionSchema.methods.getErrorByName = function(error_name, callback){
    var query = {error_name: error_name};
    User.findOne(query, callback);
}







//now we need a variable that we can access outside of this file
module.exports = mongoose.model('Submission', SubmissionSchema);